trigger:
  - main

jobs:
  - job: Build
    strategy:
      matrix:
        Windows:
          vmImage: 'windows-latest'
          assetName: 'retest-tool-windows.exe'
          isWindows: true
        macOS:
          vmImage: 'macos-latest'
          assetName: 'retest-tool-macos'
          isWindows: false
        Linux:
          vmImage: 'ubuntu-latest'
          assetName: 'retest-tool-linux'
          isWindows: false

    pool:
      vmImage: $(vmImage)

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.11'
          architecture: 'x64'

      - script: pip install -r requirements.txt pyinstaller
        displayName: Install dependencies

      - script: pyinstaller retest.spec
        displayName: Build executable

      - bash: mv dist/retest-tool dist/$(assetName)
        displayName: Rename binary (Unix)
        condition: eq(variables['isWindows'], 'false')

      - script: move dist\retest-tool.exe dist\$(assetName)
        displayName: Rename binary (Windows)
        condition: eq(variables['isWindows'], 'true')

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: dist/$(assetName)
          artifactName: $(assetName)
        displayName: Upload artifact
